# Generated by Django 4.0.6 on 2022-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_subscriber_us_categorysubscriber_subscriber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
