# Generated by Django 4.0.6 on 2022-09-24 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0005_post_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Название категории', max_length=64, null=True, unique=True, verbose_name='Name of category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Название категории', max_length=64, null=True, unique=True, verbose_name='Name of category'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_en',
            field=models.TextField(null=True, verbose_name='The content of the post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_ru',
            field=models.TextField(null=True, verbose_name='The content of the post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Post title'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Post title'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post_en',
            field=models.CharField(choices=[('NW', 'Новость'), ('AT', 'Статья')], default='NW', max_length=2, null=True, verbose_name='Post type'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post_ru',
            field=models.CharField(choices=[('NW', 'Новость'), ('AT', 'Статья')], default='NW', max_length=2, null=True, verbose_name='Post type'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_rating',
            field=models.IntegerField(default=0, help_text='Рейтинг автора', verbose_name='Author rating'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории', max_length=64, unique=True, verbose_name='Name of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(blank=True, help_text='подписчики', through='news.CategorySubscriber', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AlterField(
            model_name='categorysubscriber',
            name='category_name',
            field=models.ForeignKey(blank=True, help_text='Название категории', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AlterField(
            model_name='categorysubscriber',
            name='subscriber_user',
            field=models.ForeignKey(blank=True, help_text='подписчик', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='Время и дата комментария', verbose_name='Time and date of comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_rating',
            field=models.IntegerField(default=0, help_text='Рейтинг комментария', verbose_name='The rating of the comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postComment',
            field=models.ForeignKey(help_text='Комментарии к посту', on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Post comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Имя пользователя оставившего комментарий', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The user who commented on the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Это новая статья?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(related_name='posts', through='news.PostCategory', to='news.category', verbose_name='Post category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_create_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='Время и дата размещения', verbose_name='Time and date of publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.IntegerField(default=0, help_text='Рейтинг поста', verbose_name='The rating of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(verbose_name='The content of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=128, verbose_name='Post title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('NW', 'Новость'), ('AT', 'Статья')], default='NW', max_length=2, verbose_name='Post type'),
        ),
    ]
